name: Bug
description: Something isn't working
labels: ["type: bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should happen
  - type: input
    id: where
    attributes:
      label: Where
      placeholder: local, prod, browser/phone
